In [1]:
import numpy as np
np.set_printoptions(linewidth=1000)
import sympy as sp

from pprint import pprint

In [2]:
# Load the data from the output files
A7 = np.load("output/case_7/A.npy", allow_pickle=True)
Xd7 = np.load("output/case_7/Xd.npy", allow_pickle=True)
Yd7 = np.load("output/case_7/Yd.npy", allow_pickle=True)
Zd7 = np.load("output/case_7/Zd.npy", allow_pickle=True)

A21 = np.load("output/case_21/A.npy", allow_pickle=True)
Xd21 = np.load("output/case_21/Xd.npy", allow_pickle=True)
Yd21 = np.load("output/case_21/Yd.npy", allow_pickle=True)
Zd21 = np.load("output/case_21/Zd.npy", allow_pickle=True)

In [3]:
sp.Matrix(A7)

Matrix([
[ 2.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[-1.0,  3.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[ 0.0, -1.0,  3.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[ 0.0,  0.0, -1.0,  3.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0, -1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 

In [4]:
sp.Matrix(9 * A7)

Matrix([
[18.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[-9.0, 27.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[ 0.0, -9.0, 27.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
[ 0.0,  0.0, -9.0, 27.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0, -9.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 

In [5]:
print(Xd7)

[ 0.  0.  0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
x7_solution = np.linalg.solve(A7, Xd7)
x21_solution = np.linalg.solve(A21, Xd21)
x7_scaled = np.linalg.solve(9 * A7, 3 * Xd7)

In [7]:
np.round(x7_solution, 1)

array([-0.2, -0.3, -0.4, -0.8, -1.4, -2.4, -4. , -0.1, -0.2, -0.3, -0.5, -1. , -1.7, -2.4,  0. ,  0. ,  0. , -0. , -0.5, -1. , -1.4,  0.1,  0.2,  0.4,  1. , -0. , -0.5, -0.8,  0.2,  0.2,  0.3,  0.4,  0. , -0.3, -0.4,  0.2,  0.2,  0.2,  0.2,  0. , -0.2, -0.3,  0.2,  0.2,  0.2,  0.1,  0. , -0.1, -0.2])

In [10]:
A_scaled = 1/3 * A7
b_scaled = 1 * Xd7
phi_scaled = np.linalg.solve(A_scaled, b_scaled)
np.round(phi_scaled, 1)

array([ -0.6,  -0.8,  -1.3,  -2.4,  -4.2,  -7.1, -12. ,  -0.4,  -0.5,  -0.8,  -1.6,  -3.1,  -5.1,  -7.1,   0. ,   0. ,   0.1,  -0. ,  -1.6,  -3.1,  -4.2,   0.3,   0.5,   1.1,   3. ,  -0. ,  -1.6,  -2.4,   0.5,   0.6,   0.9,   1.1,   0.1,  -0.8,  -1.3,   0.5,   0.6,   0.6,   0.5,   0. ,  -0.5,  -0.8,   0.5,   0.5,   0.5,   0.3,   0. ,  -0.4,  -0.6])

In [143]:
np.round(x7_scaled, 2)

array([-0.06, -0.09, -0.15, -0.26, -0.47, -0.79, -1.33, -0.04, -0.05, -0.09, -0.18, -0.35, -0.57, -0.79,  0.  ,  0.  ,  0.01, -0.  , -0.17, -0.35, -0.47,  0.04,  0.06,  0.12,  0.33, -0.  , -0.18, -0.26,  0.06,  0.07,  0.1 ,  0.12,  0.01, -0.09, -0.15,  0.06,  0.06,  0.07,  0.06,  0.  , -0.05, -0.09,  0.06,  0.06,  0.06,  0.04,  0.  , -0.04, -0.06])

In [121]:
np.round(x21_solution/3, 2)

array([-0.43, -0.43, -0.45, -0.47, -0.5 , -0.54, -0.59, -0.65, -0.73, -0.83, -0.95, -1.09, -1.25, -1.45, -1.67, -1.95, -2.27, -2.65, -3.11, -3.55, -3.55, -0.42, -0.43, -0.44, -0.46, -0.49, -0.53, -0.58, -0.64, -0.71, -0.81, -0.92, -1.06, -1.22, -1.41, -1.63, -1.89, -2.2 , -2.59, -3.11, -4.  , -3.55, -0.41, -0.41, -0.43, -0.44, -0.47, -0.5 , -0.55, -0.61, -0.68, -0.77, -0.88, -1.01, -1.16, -1.34, -1.55, -1.79, -2.07, -2.38, -2.75, -3.11, -3.11, -0.39, -0.39, -0.4 , -0.42, -0.44, -0.47, -0.51, -0.56, -0.63, -0.71, -0.81, -0.94, -1.08, -1.25, -1.44, -1.65, -1.89, -2.14, -2.38, -2.59, -2.65, -0.37, -0.37, -0.38, -0.39, -0.41, -0.43, -0.46, -0.5 , -0.56, -0.63, -0.72, -0.84, -0.98, -1.13, -1.31, -1.5 , -1.69, -1.89, -2.07, -2.2 , -2.27, -0.34, -0.34, -0.35, -0.35, -0.36, -0.38, -0.4 , -0.43, -0.47, -0.53, -0.61, -0.72, -0.85, -1.  , -1.16, -1.33, -1.5 , -1.65, -1.79, -1.89, -1.95, -0.31, -0.31, -0.31, -0.31, -0.32, -0.32, -0.33, -0.34, -0.37, -0.41, -0.48, -0.58, -0.71, -0.86, -1.01,
      

In [170]:
# Construct example
A = np.array([
    [4, -1, -1],
    [-1, 4, -1],
    [-1, -1, 4]
])

b = np.array([0, 1, 0])

x = np.linalg.solve(A, b)
x

array([0.1, 0.3, 0.1])

In [193]:
A3 = 9 * A
b3 = 3 * b
x3 = np.linalg.solve(A3, b3)
x3

array([0.03333333, 0.1       , 0.03333333])

array([0.12666667, 0.06      , 0.11333333])